from random import randint

def GuessNumberGame(num,count,name):
    guess = int(input("GUESS A NUMBER BETWEEN 1 TO 100 ::: "))
    count += 1
    if guess == num:
        print(f"\nCONGRATULATIONS '{name}' , YOU GUESSED {guess} WHICH IS THE CORRECT NUMBER")
        print(f"YOU GUESSED NUMBER {guess} IN ::: {count} ATTEMPTS\n")
        return
    if guess < num:
        print(f"HIGHER NUMBER THAN {guess} !!!\n")
        GuessNumberGame(num,count,name)
    else :
        print(f"LOWER NUMBER THAN {guess} !!!\n")
        GuessNumberGame(num,count,name)

print("\nHELLO I AM YASH PANDEY")
print("LET's PLAY A GAME WHERE YOU HAVE TO GUESS A NUMBER GENERATED BY COMPUTER\n")

# It WILL GENERATE RANDOM VALUE BETWEEN 1 TO 100
name=input("Enter Your Name ::: ")
num = randint(1, 100)
GuessNumberGame(num,0,name)