# Strings Are Immutable....

name="Yash Pandey"

print(name[0:9])
# print(name[:9]) --> From Start to index 9.....
# print(name[0:]) --> from index 0 to end of string.....

# Slice from index 0 to 9 by skipping 2 char each time.....
print(name[0:11:2])
print(name[-11:-1:2])

print("\n")

'''
print(len(name)) # For length...
print(name.upper()) # For upper case...
print(name.lower()) # For lower case...
print(name.capitalize()) # Capitalize first letter...
print(name.title()) # Capitalize first letter of each word...
print(name.replace("Yash", "Yash Pandey")) # Replace "Yash" with "Yash Pandey"...
'''

print("\n")

# Easy To Understand....
print(f"String {name} Starts With 'Yas' : {name.startswith('Yas')}")
print(f"String {name} Ends With 'dey' : {name.endswith('dey')}")

print(name.find("Yash"))